@startuml Face Emotion

class ホーム画面 {
    入力されたURL
    画像情報のリスト
    選択された画像データ
    ホーム画面を表示する()
    分析結果画面に移動する()
    エラー画面に移動する()
}

class 画像表示領域 {
    画像を表示する(画像のURL)
}

class 分析結果画面 {
    分析結果データ
    分析結果を表示する()
    ホーム画面に移動する()
    エラー画面に移動する()
}

class 画像分析 {
    画像を分析する(画像のURL)
}

class グラフ領域 {
    グラフを表示する(分析結果)
}

class 表領域 {
    表を表示する(分析結果)
}

class エラー画面 {
    エラー画面を表示する(メッセージ番号)
    ホーム画面に移動する()
}

class 画像情報 {
    ID
    ユーザ名
    日付
    URL
    コンストラクタ(ユーザー名, 日付, URL)
    ゲッター()
}

class Util {
    URLの未入力を確認する()
    画像が存在するか確認する()
}

ホーム画面 "1" o.. "0..n" 画像情報
ホーム画面 ..> Util
ホーム画面 ..> 画像表示領域
ホーム画面 <..> エラー画面
ホーム画面 <..> 分析結果画面
分析結果画面 ..> 画像分析
分析結果画面 ..> 画像表示領域
分析結果画面 ..> グラフ領域
分析結果画面 ..> 表領域
分析結果画面 <..> エラー画面

@enduml