@startuml Face Emotion

class index {
    State.入力されたURL
    State.画像情報のリスト
    State.画像の選択状態のリスト
    State.選択された画像情報
    State.エラーID
    State.ディスプレイID
    画像を表示する()
    画像を選択する()
    分析結果画面に移動する()
    エラー画面に移動する()
}


class ホーム画面 {
    Prop.入力されたURL
    Prop.画像情報のリスト
    Prop.画像の選択状態のリスト
    Prop.分析可能状態
    Prop.ホーム画面を表示する()
    Prop.分析結果画面に移動する()
    Prop.エラー画面に移動する()
    Prop.分析結果画面に移動する()
    ホーム画面を表示する()
}

class 画像表示領域 {
    Prop.画像情報のリスト
    Prop.選択された画像情報
    Prop.画像を選択する()
    画像を表示する()
}

class 分析結果画面 {
    Props.選択された画像情報
    Props.ホーム画面に移動する()
    Props.エラー画面に移動する()
    画像を分析する()
    分析結果を表示する()
}

class 分析結果表示領域 {
    prop.画像情報
    prop.グラフ領域
    prop.表領域
}

class 画像分析 {
    画像を分析する(画像のURL)
}

class グラフ領域 {
    Props.分析結果データ
    グラフを表示する()
}

class 表領域 {
    Props.分析結果データ
    表を表示する()
}

class エラー画面 {
    Props.エラーID
    Props.ホーム画面に移動する()
    エラー画面を表示する()
}

class 画像情報 {
    State.ID
    State.ユーザ名
    State.日付
    State.URL
    Props.画像情報
    Props.選択状態
    コンストラクタ(ユーザー名, 日付, URL)
    ゲッター()
}

class Util {
    URLの未入力を確認する()
    画像が存在するか確認する()
}

index "1" o.. "0..n" 画像情報
index ..> ホーム画面
index ..> Util
index <..> エラー画面
index <..> 分析結果画面
ホーム画面 ..> 画像表示領域
分析結果画面 ..> 画像分析
分析結果画面 ..> グラフ領域
分析結果画面 ..> 表領域
分析結果画面 <..> エラー画面

@enduml