@startuml Face Emotion Analyzer API

' サーバーサイド
package "API" {

    package "Controller" {
        class FaceEmotionController {
            POST analyze()
        }

        class ErrorController {
            handleNotDetectedException()
            handleFaceApiException()
            handleFaceApiInvalidRequestBodyException()
            handleFaceApiInvalidRequestBodyException()
            handleInvalidMediaTypeException()
        }
    }

    package "Response" {

        class ResponseFactry {
            createSuccessResponse(): ResponseData
            createErrorResponse(): ErrorResponse
            createFaceApiErrorResponse(): FaceApiErrorResponse
        }

        class FaceApiErrorResponseDetail {
            code: string
            message: string
            getter()
            setter()
        }
        note bottom: FaceAPIからのエラー内容

        class FaceAPIExcepton {

        }

        class FaceApiInvalidRequestException {

        }

        class FaceApiServerException {

        }

        class NotDetectedException {

        }
    }


    package "Model" {
        class ResponseData {
            total: int
            mean: FaceAttributes
            peason: ResultData[]
        }

        class ResultData {
            faceId: string
            faceRectangle: FaceRectangle
            faceAttributes: FaceAttributes
        }
        note right: 成功時に返却する

        class FaceRectangle {
            top: int
            left: int
            width: int
            height: int
        }

        class FaceAttributes {
            emotion: Emotion
        }

        class Emotion {
            neutral: double
            anger : double
            contempt: double
            disgust: double
            fear: double
            happiness: double
            sadness: double
            surprise: double
        }

        class ImageInfo {
            url: string
            setter()
            getter()
        }

        class ErrorResponse {
            error: string
        }

        class ErrorMessage {
            REQUEST_BODY_ERROR = "request body is invalid.";
            MEDIA_TYPE_ERROR = "media type is invalid.";
            FACE_API_SERVER_UNABLABLE_ERROR = "Face API server unavalable.";
            FACE_API_RESPONSE_ERROR = "Face API response is error.";
            UNEXPECTED_ERROR = "unexpected error.";
        }

        note bottom: このAPIからのエラー文

        class FaceApiErrorResponse {
            error: string
            details: FaceApiError
        }
    }

    class Calculator {

    }

}

ResponseData "1" o.. "n" ResultData
ResultData "1" o.. "1" FaceRectangle
ResultData "1" o.. "1" FaceAttributes
FaceAttributes "1" o.. "1" Emotion

FaceEmotionController ..> ResponseData
FaceEmotionController ..> ErrorController

Controller ..> ErrorMessage
ResponseFactry ..> ErrorMessage

FaceEmotionController ..> ResponseFactry
ErrorController ..> ResponseFactry
ResponseFactry ..> ErrorResponse
ResponseFactry ..> FaceApiErrorResponse
FaceApiErrorResponse ..> FaceApiErrorResponseDetail
Response ..> ResultData

@enduml