@startuml
title UC02 画像を分析する

actor ユーザー
participant ホーム画面
participant 分析結果画面
participant 画像分析
participant エラー画面
actor 画像分析システム
activate ホーム画面
ユーザー -> ホーム画面 : 画像を選択
note right : チェックボックスの状態を検知する

alt 画像が1つだけ選択されている場合
    ホーム画面 -> ホーム画面 : 分析ボタン押下可能状態に変更
else 
    ホーム画面 -> ホーム画面 : 分析ボタン押下不可状態に変更
end
ユーザー <-- ホーム画面 : ボタンの状態をホーム画面に反映

ユーザー -> ホーム画面 : 分析ボタンを押下
note right : ボタンのクリックを検知する
ホーム画面 -> 分析結果画面 : 分析結果画面を表示する(選択された画像情報)
deactivate ホーム画面
activate 分析結果画面
分析結果画面 -> 画像分析 : 画像を分析する(選択された画像情報のURL)
activate 画像分析
画像分析 -> 画像分析システム : 分析要求
activate 画像分析システム
画像分析 <-- 画像分析システム : 分析結果
deactivate 画像分析システム
分析結果画面 <-- 画像分析 : 分析結果
deactivate 画像分析

alt 分析結果が正常の場合
    ユーザー <-- 分析結果画面 : 分析結果画面表示
    note right : 画像とグラフを表示。分析データが複数の場合は分析可能人数分までのデータを表示
    
    ユーザー -> 分析結果画面 : 戻るボタンを押下
    ユーザー <-- 分析結果画面 : ホーム画面表示

else 分析結果がエラーの場合
    分析結果画面 -> エラー画面 : エラー画面を表示する(メッセージ番号)
    activate エラー画面
    ユーザー <-- エラー画面 : エラー画面表示
    deactivate エラー画面
end

@enduml